import Html exposing (node, div, ul, li, span, a, details, summary, text, img, strong, form, input, button)
import Html.Attributes exposing (attribute, class, name, value, action, method, style, href, alt, src, height, width, id)
import Svg exposing (svg, path)
import Svg.Attributes exposing (d, viewBox, version)

view = 
    div [ class "d-lg-flex" ]
        [ ul [ class "user-nav d-lg-flex flex-items-center list-style-none", id "user-links" ]
            [ li [ class "dropdown" ]
                [ span [ class "d-none d-lg-block  px-2" ]
                    [ a [ attribute "aria-label" "You have unread notifications", class "notification-indicator tooltipped tooltipped-s my-2 my-lg-0 js-socket-channel js-notification-indicator", attribute "data-hotkey" "g n", attribute "data-ga-click" "Header, go to notifications, icon:unread", attribute "data-channel" "notification-changed:5099105", href "/notifications" ]
                        [ span [ class "mail-status unread" ]
                            []
                        , svg [ Svg.Attributes.class "octicon octicon-bell", viewBox "0 0 14 16", version "1.1", Svg.Attributes.width "14", Svg.Attributes.height "16" ]
                            [ path [ d "M13.99 11.991v1H0v-1l.73-.58c.769-.769.809-2.547 1.189-4.416.77-3.767 4.077-4.996 4.077-4.996 0-.55.45-1 .999-1 .55 0 1 .45 1 1 0 0 3.387 1.229 4.156 4.996.38 1.879.42 3.657 1.19 4.417l.659.58h-.01zM6.995 15.99c1.11 0 1.999-.89 1.999-1.999H4.996c0 1.11.89 1.999 1.999 1.999z" ]
                                []
                            ]
                        ]
                    ]
                ]
            , li [ class "dropdown" ]
                [ details [ class "details-overlay details-reset d-none d-lg-flex px-lg-2 py-2 py-lg-0 flex-items-center" ]
                    [ summary [ class "HeaderNavlink", attribute "aria-label" "Create new\8230", attribute "data-ga-click" "Header, create new, icon:add", attribute "aria-haspopup" "menu" ]
                        [ svg [ Svg.Attributes.class "octicon octicon-plus float-left mr-1 mt-1", viewBox "0 0 12 16", version "1.1", Svg.Attributes.width "12", Svg.Attributes.height "16" ]
                            [ path [ d "M12 9H7v5H5V9H0V7h5V2h2v5h5v2z" ]
                                []
                            ]
                        , span [ class "dropdown-caret mt-1" ]
                            []
                        ]
                    , node "details-menu" [ class "dropdown-menu dropdown-menu-sw", attribute "role" "menu" ]
                        [ a [ attribute "role" "menuitem", class "dropdown-item", href "/new", attribute "data-ga-click" "Header, create new repository" ]
                            [ text "New repository"
                            ]
                        , a [ attribute "role" "menuitem", class "dropdown-item", href "/new/import", attribute "data-ga-click" "Header, import a repository" ]
                            [ text "Import repository"
                            ]
                        , a [ attribute "role" "menuitem", class "dropdown-item", href "https://gist.github.com/", attribute "data-ga-click" "Header, create new gist" ]
                            [ text "New gist"
                            ]
                        , a [ attribute "role" "menuitem", class "dropdown-item", href "/organizations/new", attribute "data-ga-click" "Header, create new organization" ]
                            [ text "New organization"
                            ]
                        ]
                    ]
                ]
            , li [ class "dropdown" ]
                [ a [ class "d-lg-none HeaderNavlink name tooltipped tooltipped-sw px-lg-2 py-2 py-lg-0", href "/isomoar", attribute "aria-label" "View profile and more", attribute "aria-expanded" "false", attribute "aria-haspopup" "false" ]
                    [ span [ class "text-bold" ]
                        [ text "isomoar"
                        ]
                    ]
                , details [ class "details-overlay details-reset d-none d-lg-flex pl-lg-2 py-2 py-lg-0 flex-items-center" ]
                    [ summary [ class "HeaderNavlink name mt-1", attribute "aria-label" "View profile and more", attribute "data-ga-click" "Header, show menu, icon:avatar", attribute "aria-haspopup" "menu" ]
                        [ span [ class "dropdown-caret" ]
                            []
                        ]
                    , node "details-menu" [ class "dropdown-menu dropdown-menu-sw", attribute "role" "menu" ]
                        [ ul []
                            [ li [ class "header-nav-current-user css-truncate" ]
                                [ a [ attribute "role" "menuitem", class "no-underline user-profile-link px-3 pt-2 pb-2 mb-n2 mt-n1 d-block", href "/isomoar", attribute "data-ga-click" "Header, go to profile, text:Signed in as" ]
                                    [ text "Signed in as"
                                    , strong [ class "css-truncate-target" ]
                                        [ text "isomoar"
                                        ]
                                    ]
                                ]
                            , li [ class "dropdown-divider" ]
                                []
                            , li []
                                [ a [ attribute "role" "menuitem", class "dropdown-item", href "/isomoar", attribute "data-ga-click" "Header, go to profile, text:your profile" ]
                                    [ text "Your profile"
                                    ]
                                ]
                            , li []
                                [ a [ attribute "role" "menuitem", class "dropdown-item", href "/isomoar?tab=repositories", attribute "data-ga-click" "Header, go to repositories, text:your repositories" ]
                                    [ text "Your repositories"
                                    ]
                                ]
                            , li []
                                [ a [ attribute "role" "menuitem", class "dropdown-item", href "/isomoar?tab=stars", attribute "data-ga-click" "Header, go to starred repos, text:your stars" ]
                                    [ text "Your stars"
                                    ]
                                ]
                            , li []
                                [ a [ attribute "role" "menuitem", class "dropdown-item", href "https://gist.github.com/", attribute "data-ga-click" "Header, your gists, text:your gists" ]
                                    [ text "Your gists"
                                    ]
                                ]
                            , li [ class "dropdown-divider" ]
                                []
                            , li []
                                [ a [ attribute "role" "menuitem", class "dropdown-item", href "https://help.github.com", attribute "data-ga-click" "Header, go to help, text:help" ]
                                    [ text "Help"
                                    ]
                                ]
                            , li []
                                [ a [ attribute "role" "menuitem", class "dropdown-item", href "/settings/profile", attribute "data-ga-click" "Header, go to settings, icon:settings" ]
                                    [ text "Settings"
                                    ]
                                ]
                            , li []
                                [ form [ class "logout-form", action "/logout", Html.Attributes.acceptCharset "UTF-8", method "post" ]
                                    [ button [ Html.Attributes.type_ "submit", class "dropdown-item dropdown-signout", attribute "data-ga-click" "Header, sign out, icon:logout", attribute "role" "menuitem" ]
                                        [ text "Sign out"
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        , form [ class "d-lg-none", action "/logout", Html.Attributes.acceptCharset "UTF-8", method "post" ]
            [ button [ Html.Attributes.type_ "submit", class "btn-link HeaderNavlink d-block width-full text-left py-2 text-bold", attribute "data-ga-click" "Header, sign out, icon:logout", style [("padding-left", "2px")] ]
                [ svg [ Svg.Attributes.class "octicon octicon-sign-out v-align-middle", Svg.Attributes.style "margin-right: 2px;", viewBox "0 0 16 16", version "1.1", Svg.Attributes.width "16", Svg.Attributes.height "16" ]
                    [ path [ d "M11.992 8.994V6.996H7.995v-2h3.997V2.999l3.998 2.998-3.998 2.998zm-1.998 2.998H5.996V2.998L2 1h7.995v2.998h1V1c0-.55-.45-.999-1-.999H.999A1.001 1.001 0 0 0 0 1v11.372c0 .39.22.73.55.91L5.996 16v-3.008h3.998c.55 0 1-.45 1-1V7.996h-1v3.998z" ]
                        []
                    ]
                , text "Sign out"
                ]
            ]
        , form [ class "sr-only right-0", action "/logout", Html.Attributes.acceptCharset "UTF-8", method "post" ]
            [ button [ Html.Attributes.type_ "submit", class "dropdown-item dropdown-signout", attribute "data-ga-click" "Header, sign out, icon:logout" ]
                [ text "Sign out"
                ]
            ]
        ]
